services:
  mongo:
    container_name: mongoDb
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
      - ./init-replica-set.sh:/docker-entrypoint-initdb.d/init-replica-set.sh

    ports:
      - "27017:27017"
